/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    PersonDetail: typeof import('./components/PersonDetail/index.vue')['default']
    PullList: typeof import('./components/pullList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserForm: typeof import('./components/FormCell/userForm.vue')['default']
    WaterfallsFlow: typeof import('./components/WaterfallsFlow/WaterfallsFlow.vue')['default']
    WaterfallsFlowItem: typeof import('./components/WaterfallsFlowItem/WaterfallsFlowItem.vue')['default']
  }
}
